-- RESET
DROP TABLE A_USER;
DROP TABLE A_MESSAGE;

-- Create user
CREATE TABLE A_USER
    (ID Serial PRIMARY KEY,
    NAME_STRING VARCHAR(255) NOT NULL,
    MAIL VARCHAR(255) NOT NULL,
    PW_SH5 VARCHAR(255),
    INVEST_TYPE VARCHAR(255),
    INVESST_EXP VARCHAR(255),
    D_CREATED TIMESTAMP,
    D_LAST_LOGIN TIMESTAMP);
    
    
CREATE TABLE A_MESSAGE
    (ID SERIAL PRIMARY KEY,
    FROM_NAME VARCHAR(255),
    FROM_MAIL VARCHAR(255),
    MESSAGE_TEXT TEXT,
    MESSAGE_DATE TIMESTAMP);

CREATE OR REPLACE FUNCTION set_current_date()   
RETURNS TRIGGER AS $$
BEGIN
    NEW.D_CREATED = now();
    NEW.D_LAST_LOGIN = now();
    RETURN NEW;   
END;
$$ language 'plpgsql';

CREATE OR REPLACE TRIGGER set_current_date_trigger BEFORE INSERT ON a_user FOR EACH ROW EXECUTE PROCEDURE  set_current_date();
