-- RESET
DROP TABLE messages;
DROP TABLE A_USER;
DROP TABLE A_MESSAGE;

-- Create user
CREATE TABLE A_USER
    (ID NUMERIC,
    NAME_STRING VARCHAR(255),
    MAIL VARCHAR(255),
    PW_SH5 VARCHAR(255),
    D_CREATED TIMESTAMP,
    D_LAST_LOGIN TIMESTAMP,
    CONSTRAINT USER_PK PRIMARY KEY(ID));
    
    
CREATE TABLE A_MESSAGE
    (ID NUMERIC,
    FROM_NAME VARCHAR(255),
    FROM_MAIL VARCHAR(255),
    MESSAGE_TEXT TEXT,
    MESSAGE_DATE TIMESTAMP,
    CONSTRAINT MESSAGE_PK PRIMARY KEY(ID));
